apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: pre-filtro-spark-app
  namespace: spark
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "artifactory.alpenet.com.br/docker-snapshot/alpe/etl-bureau-to-trusted:1.0.80-SNAPSHOT"
  imagePullSecrets: ["artifactory-docker"]
  imagePullPolicy: Always
  mainApplicationFile: local:///scripts/repo/dags/receita_federal/spark/script/pre_filtro.py
  sparkVersion: "3.5.1"
  deps:
    repositories:
      - https://artifactory.alpenet.com.br/artifactory/maven-local/
    packages:
      - io.delta:delta-core_2.12:2.4.0
      - io.delta:delta-storage:2.4.0
      # - io.delta:delta-spark_2.12:3.2.0
      - org.apache.spark:spark-catalyst_2.12:3.5.1
      - org.apache.hadoop:hadoop-aws:3.3.4
      - org.apache.hadoop:hadoop-common:3.3.4
      - org.apache.hadoop:hadoop-hdfs:3.3.4
      - software.amazon.awssdk:sdk-core:2.25.24
      - software.amazon.awssdk:s3-transfer-manager:2.25.24
      - software.amazon.awssdk:auth:2.25.24
      - software.amazon.awssdk:identity-spi:2.25.24
      - software.amazon.awssdk:s3:2.25.24
      - software.amazon.awssdk:aws-core:2.25.24
      - software.amazon.awssdk:utils:2.25.24
      - software.amazon.awssdk:regions:2.25.24
      - software.amazon.awssdk:aws-json-protocol:2.25.24
      - software.amazon.awssdk:json-utils:2.25.24
      - software.amazon.awssdk:third-party-jackson-core:2.25.24
      - software.amazon.awssdk:http-client-spi:2.25.24
      - io.trino:trino-jdbc:443
    pyFiles:
      - local:///app/dependencies/trino-python-conect-core-1.0.0.zip
  restartPolicy:
    type: OnFailure
  sparkConf:
    "spark.sql.extensions": "io.delta.sql.DeltaSparkSessionExtension"
    "spark.sql.catalog.spark_catalog": "org.apache.spark.sql.delta.catalog.DeltaCatalog"
    "spark.hadoop.security.authentication": "simple"
    "spark.hadoop.security.authorization": "false"
  driver:
    deleteOnTermination: true
    coreLimit: "1"
    coreRequest: "500m"
    memory: "2048m"
    labels:
      version: "3.5.1"
    serviceAccount: spark-operator
    volumeMounts:
      - name: "spark-scripts-volume"
        mountPath: "/scripts"
    annotations:
      sidecar.istio.io/inject: "false"
    env:
      - name: MINIO_TRUSTED_ENDPOINT
        valueFrom:
          secretKeyRef:
            name: spark-secrets
            key: MINIO_TRUSTED_ENDPOINT
      - name: MINIO_TRUSTED_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: spark-secrets
            key: MINIO_TRUSTED_ACCESS_KEY
      - name: MINIO_TRUSTED_SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: spark-secrets
            key: MINIO_TRUSTED_SECRET_KEY
      - name: MINIO_REFINED_ENDPOINT
        valueFrom:
          secretKeyRef:
            name: spark-secrets
            key: MINIO_REFINED_ENDPOINT
      - name: MINIO_REFINED_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: spark-secrets
            key: MINIO_REFINED_ACCESS_KEY
      - name: MINIO_REFINED_SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: spark-secrets
            key: MINIO_REFINED_SECRET_KEY
      - name: MINIO_RAW_ENDPOINT
        valueFrom:
          secretKeyRef:
            name: spark-secrets
            key: MINIO_RAW_ENDPOINT
      - name: MINIO_RAW_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: spark-secrets
            key: MINIO_RAW_ACCESS_KEY
      - name: MINIO_RAW_SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: spark-secrets
            key: MINIO_RAW_SECRET_KEY
    initContainers:
      - name: git-sync
        image: "k8s.gcr.io/git-sync/git-sync:v3.6.1"
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: spark-scripts-volume
            mountPath: /scripts
        env:
          - name: GIT_SYNC_REPO
            value: "https://bitbucket.org/timefinanceiro/airflow-dags.git"
          - name: GIT_SYNC_BRANCH
            value: "master"
          - name: GIT_SYNC_ROOT
            value: /scripts
          - name: GIT_SYNC_DEST
            value: "repo"
          - name: GIT_SYNC_ONE_TIME
            value: "true"
          - name: GIT_SYNC_SSH
            value: "false" 
          - name: GIT_SYNC_AUTH
            value: "basic"
          - name: GIT_SYNC_REV
            value: HEAD
          - name: GIT_SYNC_DEPTH
            value: "1"
          - name: GIT_SYNC_WAIT
            value: "30"
          - name: GIT_SYNC_TIMEOUT
            value: "120"
          - name: GIT_SYNC_ADD_USER
            value: "true"
          - name: GIT_SYNC_MAX_SYNC_FAILURES
            value: "0"
          - name: GIT_SYNC_SUBMODULES
            value: "recursive"
          - name: GIT_KNOWN_HOSTS
            value: "false"
          - name: GIT_SYNC_USERNAME
            valueFrom:
              secretKeyRef:
                key: username
                name: bitbucket-spark-access
          - name: GIT_SYNC_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: bitbucket-spark-access
      - name: permission-fix
        image: busybox
        command: ["sh", "-c", "chmod -R 777 /scripts/repo && chmod -R 777 /scripts/*"]
        volumeMounts:
          - name: spark-scripts-volume
            mountPath: /scripts
  executor:
    deleteOnTermination: true
    coreLimit: "1"
    coreRequest: "500m"
    instances: 1
    memory: "3072m"
    memoryOverhead: "1024m"
    labels:
      version: "3.5.1"
    volumeMounts:
      - name: "spark-scripts-volume"
        mountPath: "/scripts"
    annotations:
      sidecar.istio.io.inject: "false"
    env:
      - name: MINIO_TRUSTED_ENDPOINT
        valueFrom:
          secretKeyRef:
            name: spark-secrets
            key: MINIO_TRUSTED_ENDPOINT
      - name: MINIO_TRUSTED_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: spark-secrets
            key: MINIO_TRUSTED_ACCESS_KEY
      - name: MINIO_TRUSTED_SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: spark-secrets
            key: MINIO_TRUSTED_SECRET_KEY
      - name: MINIO_REFINED_ENDPOINT
        valueFrom:
          secretKeyRef:
            name: spark-secrets
            key: MINIO_REFINED_ENDPOINT
      - name: MINIO_REFINED_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: spark-secrets
            key: MINIO_REFINED_ACCESS_KEY
      - name: MINIO_REFINED_SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: spark-secrets
            key: MINIO_REFINED_SECRET_KEY
      - name: MINIO_RAW_ENDPOINT
        valueFrom:
          secretKeyRef:
            name: spark-secrets
            key: MINIO_RAW_ENDPOINT
      - name: MINIO_RAW_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: spark-secrets
            key: MINIO_RAW_ACCESS_KEY
      - name: MINIO_RAW_SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: spark-secrets
            key: MINIO_RAW_SECRET_KEY
    initContainers:
      - name: git-sync
        image: "k8s.gcr.io/git-sync/git-sync:v3.6.1"
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: spark-scripts-volume
            mountPath: /scripts
        env:
          - name: GIT_SYNC_REPO
            value: "https://bitbucket.org/timefinanceiro/airflow-dags.git"
          - name: GIT_SYNC_BRANCH
            value: "master"
          - name: GIT_SYNC_ROOT
            value: /scripts
          - name: GIT_SYNC_DEST
            value: "repo"
          - name: GIT_SYNC_ONE_TIME
            value: "true"
          - name: GIT_SYNC_SSH
            value: "false" 
          - name: GIT_SYNC_AUTH
            value: "basic"
          - name: GIT_SYNC_REV
            value: HEAD
          - name: GIT_SYNC_DEPTH
            value: "1"
          - name: GIT_SYNC_WAIT
            value: "30"
          - name: GIT_SYNC_TIMEOUT
            value: "120"
          - name: GIT_SYNC_ADD_USER
            value: "true"
          - name: GIT_SYNC_MAX_SYNC_FAILURES
            value: "0"
          - name: GIT_SYNC_SUBMODULES
            value: "recursive"
          - name: GIT_KNOWN_HOSTS
            value: "false"
          - name: GIT_SYNC_USERNAME
            valueFrom:
              secretKeyRef:
                key: username
                name: bitbucket-spark-access
          - name: GIT_SYNC_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: bitbucket-spark-access
      - name: permission-fix
        image: busybox
        command: ["sh", "-c", "chmod -R 777 /scripts/repo && chmod -R 777 /scripts/*"]
        volumeMounts:
          - name: spark-scripts-volume
            mountPath: /scripts
  volumes:
    - name: "spark-scripts-volume"
      persistentVolumeClaim:
        claimName: pvc-efs-spark
